name = "auth"
main = "src/main.ts"
compatibility_date = "2025-11-06"

[vars]
ENVIRONMENT = "production"
AUTH_GUI_URL = "https://auth.vpbank.workers.dev"
AUTH_API_URL = "https://auth.vpbank.workers.dev"
ADMIN_GUI_URL = "https://appraiser.pages.dev"
EMAIL_FROM = "{{EMAIL_ADDRESS}}"
JWT_SECRET = "{{JWT_SECRET}}"
EMAIL_API_KEY = "{{EMAIL_API_KEY}}"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[dev.vars]
ENVIRONMENT = "development"
AUTH_GUI_URL = "http://localhost:8787"
AUTH_API_URL = "http://localhost:8787"
ADMIN_GUI_URL = "http://localhost:3002"
EMAIL_FROM = "{{EMAIL_ADDRESS}}"
JWT_SECRET = "{{JWT_SECRET}}"
EMAIL_API_KEY = "{{EMAIL_API_KEY}}"

[[d1_databases]]
binding = "DB"
database_name = "valumind-auth-db"
database_id = "3bea4c95-7c28-4a1c-8ae8-1159726b27c7"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1