# auth/wrangler.toml
name = "auth"
main = "src/main.ts"
compatibility_date = "2025-10-17"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "valumind-auth-db"
database_id = "3bea4c95-7c28-4a1c-8ae8-1159726b27c7"