name = "admin"
compatibility_date = "2024-11-06"
pages_build_output_dir = "out"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[app_cache]]
binding = "app_cache"
id = "e12207eca0bb41d6b801beef00fddfe5" # You need to replace this with your actual KV namespace ID
preview_id = "e12207eca0bb41d6b801beef00fddfe5" # You need to replace this with your actual preview KV namespace ID
